/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shut.down;
/**
 *
 * @author Darsheet Patel
 */
public class Shut extends javax.swing.JFrame {

    /**
     * Creates new form Shut
     */
    public Shut() {
        initComponents();
        jLabel2.setText("© 2014 Darsheet Patel");
        disp.setText("Close all your apps and turn off your PC.");
        disp1.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        disp = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        disp1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shut Down Windows");
        setMinimumSize(new java.awt.Dimension(720, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        cb.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shut Down", "Restart", "Log Out" }));
        cb.setToolTipText("");
        cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemStateChanged(evt);
            }
        });
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        getContentPane().add(cb);
        cb.setBounds(30, 60, 270, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 150, 90, 29);

        disp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        disp.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(disp);
        disp.setBounds(30, 100, 340, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 150, 60, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("What do you want the computer to do?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 20, 290, 30);

        disp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        disp1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(disp1);
        disp1.setBounds(30, 120, 340, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© 2014 Darsheet Patel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 500, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shut/down/Screen Shot 2014-02-02 at 2.06.23 PM.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 720, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String val=(String)cb.getSelectedItem();
        if(val.equals("Shut Down"))
        {
            Runtime abc=Runtime.getRuntime();
            try
            {
                abc.exec("shutdown -s");
            }
            catch(Exception ex){}
            System.exit(0);
        }
        if(val.equals("Restart"))
        {
            Runtime abc=Runtime.getRuntime();
            try
            {
                abc.exec("shutdown -r");
            }
            catch(Exception ex){}
            System.exit(0);
        }
        if(val.equals("Log Out"))
        {
            Runtime abc=Runtime.getRuntime();
            try
            {
                abc.exec("shutdown -l");
            }
            catch(Exception ex){}
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemStateChanged
        // TODO add your handling code here:
        String val=(String)cb.getSelectedItem();
        if(val.equals("Shut Down"))
        {
            disp.setText("Close all your apps and turn off your PC.");
            disp1.setText("");
        }
        if(val.equals("Restart"))
        {
            disp.setText("Close all your apps, turn off the PC and");
            disp1.setText("turn it on again.");
        }
        if(val.equals("Log Out"))
        {
            disp.setText("Close all your and log you out.");
            disp1.setText("");
        }
    }//GEN-LAST:event_cbItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Shut().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb;
    private javax.swing.JLabel disp;
    private javax.swing.JLabel disp1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
